"""
*********1*********2*********3*********4*********5*********6*********7*********8
*2345678901234567890123456789012345678901234567890123456789012345678901234567890
********************************************************************************
******************* File generated by Aqwa in Workbench 2023 R1 ****************
********************************************************************************
* Project Title                   : 
* Project Reference               : 
* Project Author                  : 
* Project Description             : 
* Date of Creation                : 2022/9/24 21:18:39
* Last Modified                   : 2023/12/13 11:10:44
* This analysis file written at   : 2024/8/17 13:30:52
* Hydrodynamic Solver Unit System : Metric: kg, m [N]
********************************************************************************
"""
################################################################################################
# The following variables are accessible in the Workbench process environment:
#
# AQWA_INPUT_FILE: points to the Aqwa input .DAT file generated for the current analysis.
# AQWA_INPUT_FILE_NOEXT: as above, but without the file extension.
# AQWA_WORK_DIR: the Aqwa solve files directory for the current analysis.
# AQWA_USER_DIR: the project user_files directory.
# AQWA_INSTALL_DIR: the root directory of the ANSYS installation.
# AQWA_PYTHON_EXE: the path to the CPython executable (included with the ANSYS installation).
#
# sys.stderr points to [AQWA_WORK_DIR]\PreSolveErr.txt
# sys.stdout points to [AQWA_WORK_DIR]\PreSolveOut.txt
# For convenience, these environment variables are retrieved and stored in global variables.
# Feel free to delete this code if it is not useful to your Python script.
################################################################################################

import os
import sys

AqwaInputFile = os.environ["AQWA_INPUT_FILE"]
AqwaInputFileNoExt = os.environ["AQWA_INPUT_FILE_NOEXT"]
AqwaWorkDir = os.environ["AQWA_WORK_DIR"]
AqwaUserFilesDir = os.environ["AQWA_USER_DIR"]
AqwaInstallDir = os.environ["AQWA_INSTALL_DIR"]
AqwaPythonExe = os.environ["AQWA_PYTHON_EXE"]

for ext in [".PLD",".PLS"]:
    open(AqwaInputFileNoExt + ext,"a").close()