"""
*********1*********2*********3*********4*********5*********6*********7*********8
*2345678901234567890123456789012345678901234567890123456789012345678901234567890
********************************************************************************
******************* File generated by Aqwa in Workbench 2020 R2 ****************
********************************************************************************
* Project Title                   : 
* Project Reference               : 
* Project Author                  : 
* Project Description             : 
* Date of Creation                : 2022/9/24 21:18:39
* Last Modified                   : 2022/10/6 15:32:29
* This analysis file written at   : 2022/10/6 21:31:08
* Hydrodynamic Solver Unit System : Metric: kg, m [N]
********************************************************************************
"""
################################################################################################
# The following variables are accessible in the Workbench process environment:
#
# AQWA_INPUT_FILE: points to the Aqwa input .DAT file generated for the current analysis.
# AQWA_INPUT_FILE_NOEXT: as above, but without the file extension.
# AQWA_WORK_DIR: the Aqwa solve files directory for the current analysis.
# AQWA_USER_DIR: the project user_files directory.
# AQWA_INSTALL_DIR: the root directory of the ANSYS installation.
# AQWA_PYTHON_EXE: the path to the CPython executable (included with the ANSYS installation).
# AQWA_RUN_COMPLETED: set to either "TRUE" or "FALSE" depending on the outcome of the Solve.
#
# sys.stderr points to [AQWA_WORK_DIR]\PostSolveErr.txt
# sys.stdout points to [AQWA_WORK_DIR]\PostSolveOut.txt
# For convenience, these environment variables are retrieved and stored in global variables.
# Feel free to delete this code if it is not useful to your Python script.
################################################################################################

import os
import sys

AqwaInputFile = os.environ["AQWA_INPUT_FILE"]
AqwaInputFileNoExt = os.environ["AQWA_INPUT_FILE_NOEXT"]
AqwaWorkDir = os.environ["AQWA_WORK_DIR"]
AqwaUserFilesDir = os.environ["AQWA_USER_DIR"]
AqwaInstallDir = os.environ["AQWA_INSTALL_DIR"]
AqwaPythonExe = os.environ["AQWA_PYTHON_EXE"]
AqwaRunCompleted = os.environ["AQWA_RUN_COMPLETED"]

exprot CSV file(RAO);
